/*import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
 // submodule 2
  await page.goto('http://localhost:5175/login');
  await page.getByRole('button', { name: 'Subsystem Admin · Administrative Office admin@ems.ph / admin123 Use →' }).click();
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Transactions' }).click();
  await page.getByRole('link', { name: 'View' }).nth(1).click();
  await page.getByRole('combobox').click();
  await page.locator('html').click();
  await page.getByRole('button', { name: 'JM John Michael Garcia' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Subsystem Admin · OSAS' }).click();
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Transactions' }).click();
  await page.getByRole('link', { name: 'View' }).first().click();
  // submodule 3
  await page.getByRole('button', { name: 'MR Mikhail Reveche subsystem' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Staff · Administrative Office' }).click();
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Transactions' }).click();
  await page.getByRole('row', { name: 'Facility Reservation Request' }).getByRole('link').click();
  await page.getByText('CompleteIncompleteFor').click();
  await page.getByRole('button', { name: 'Complete', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Mark In Progress' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  // submodule 4
  await page.getByRole('link', { name: 'Back to Transaction' }).click();
  await page.getByRole('row', { name: 'Facility Reservation Request' }).getByRole('link').click();
  await page.getByRole('button', { name: 'Incomplete' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'For Compliance' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Complete', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  // submodule 1
  await page.getByRole('link', { name: 'Back to Transaction' }).click();
  await page.getByRole('button', { name: 'New Transaction' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Select a service…' }).click();
  await page.getByText('Campus Equipment / Materials Borrowing', { exact: true }).click();
  await page.getByRole('combobox').filter({ hasText: 'Student' }).click();
  await page.locator('.fixed.inset-0').click();
  await page.getByRole('combobox').filter({ hasText: 'Student' }).click();
  await page.getByLabel('Student').getByText('Student', { exact: true }).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('Rodbenedict');
  await page.getByRole('textbox', { name: 'First Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Middle Name (Optional)' }).press('Tab');
  await page.getByRole('textbox', { name: 'Surname' }).fill('Tablizo');
  await page.getByRole('textbox', { name: 'e.g., BSIT (BS Information' }).click();
  await page.getByRole('textbox', { name: 'e.g., BSIT (BS Information' }).fill('BSIT');
  await page.getByRole('textbox', { name: '09XXXXXXXXX' }).click();
  await page.getByRole('textbox', { name: '09XXXXXXXXX' }).fill('09652365985');
  await page.getByRole('combobox').filter({ hasText: 'Select year level' }).click();
  await page.getByRole('option', { name: '3rd Year' }).click();
  await page.getByRole('button', { name: 'Submit Transaction' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
});*/

import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5175/login');
  await page.getByRole('button', { name: 'Subsystem Admin · Administrative Office admin@ems.ph / admin123 Use →' }).click();
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Transactions' }).click();
  await page.getByRole('link', { name: 'View' }).nth(1).click();
  await page.getByRole('combobox').click();
  await page.locator('html').click();
  await page.getByRole('button', { name: 'JM John Michael Garcia' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Subsystem Admin · OSAS' }).click();
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Transactions' }).click();
  await page.getByRole('link', { name: 'View' }).first().click();
  await page.getByRole('button', { name: 'MR Mikhail Reveche subsystem' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Staff · Administrative Office' }).click();
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Transactions' }).click();
  await page.getByRole('row', { name: 'Facility Reservation Request' }).getByRole('link').click();
  await page.getByText('CompleteIncompleteFor').click();
  await page.getByRole('button', { name: 'Complete', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Mark In Progress' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('link', { name: 'Back to Transaction' }).click();
  await page.getByRole('row', { name: 'Facility Reservation Request' }).getByRole('link').click();
  await page.getByRole('button', { name: 'Incomplete' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'For Compliance' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Complete', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('link', { name: 'Back to Transaction' }).click();
  await page.getByRole('button', { name: 'New Transaction' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Select a service…' }).click();
  await page.getByText('Campus Equipment / Materials Borrowing', { exact: true }).click();
  await page.getByRole('combobox').filter({ hasText: 'Student' }).click();
  await page.locator('.fixed.inset-0').click();
  await page.getByRole('combobox').filter({ hasText: 'Student' }).click();
  await page.getByLabel('Student').getByText('Student', { exact: true }).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('Rodbenedict');
  await page.getByRole('textbox', { name: 'First Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Middle Name (Optional)' }).press('Tab');
  await page.getByRole('textbox', { name: 'Surname' }).fill('Tablizo');
  await page.getByRole('textbox', { name: 'e.g., BSIT (BS Information' }).click();
  await page.getByRole('textbox', { name: 'e.g., BSIT (BS Information' }).fill('BSIT');
  await page.getByRole('textbox', { name: '09XXXXXXXXX' }).click();
  await page.getByRole('textbox', { name: '09XXXXXXXXX' }).fill('09652365985');
  await page.getByRole('combobox').filter({ hasText: 'Select year level' }).click();
  await page.getByRole('option', { name: '3rd Year' }).click();
  await page.getByRole('button', { name: 'Submit Transaction' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
});