import type { Office, Service, Transaction, TransactionStatusHistory } from '@/types'
import { parseSlaToSeconds } from './timeUtils'

// ─── Offices ─────────────────────────────────────────────────────────────────

export const OFFICES: Office[] = [
  { id: 'off-1', name: 'Administrative Office', code: 'ADMIN_OFFICE' },
  { id: 'off-2', name: 'Academic Office', code: 'ACADEMIC_OFFICE' },
  { id: 'off-3', name: 'Office of Student Affairs and Services', code: 'OSAS' },
]

// ─── Services (from OPCR SLA CSV) ────────────────────────────────────────────

const svc = (
  id: string,
  name: string,
  category: string,
  clientType: string,
  officeId: string,
  officeCode: string,
  slaDisplay: string,
): Service => ({
  id,
  name,
  category: category as Service['category'],
  client_type: clientType,
  office_id: officeId,
  office_code: officeCode as Service['office_code'],
  sla_target_seconds: parseSlaToSeconds(slaDisplay),
  sla_display: slaDisplay,
  is_active: true,
  is_na: false,   // EMS-004: default to false; set true for N/A (placeholder) services
})

export const MOCK_SERVICES: Service[] = [
  // OSAS (Student Services)
  svc('svc-25', 'Application for New Identification Card', 'ID Services', 'Student', 'off-3', 'OSAS', '30 min'),
  svc('svc-26', 'ID Replacement', 'ID Services', 'Student', 'off-3', 'OSAS', '30 min'),
  svc('svc-27', 'Consultation Service', 'Consultation', 'Student', 'off-3', 'OSAS', '28 min'),
  svc('svc-28', 'Counseling Service', 'Counseling', 'Student', 'off-3', 'OSAS', '44 min'),
  svc('svc-29', 'Issuance of Recommendation Letter', 'Recommendation', 'Student / Alumni', 'off-3', 'OSAS', '50 min'),
  svc('svc-30', 'Permission to Conduct an Activity (OSAS)', 'Activity Permit', 'Student / Organization', 'off-3', 'OSAS', '1 hr, 15 min'),
  svc('svc-36', 'Off-Campus Activity Permission', 'Activity Permit', 'Student / Organization', 'off-3', 'OSAS', '1 hr, 15 min'),
  svc('svc-31', 'Processing of Application for Student Fund-Raising', 'Activity Permit', 'Student / Organization', 'off-3', 'OSAS', '1 day'),
  svc('svc-32', 'Student Development Permission (OSAS)', 'Activity Permit', 'Student / Organization', 'off-3', 'OSAS', '7 min'),
  svc('svc-33', 'Processing of Request for Informative Copy of Grades', 'Records', 'Student', 'off-3', 'OSAS', '1 day'),
  svc('svc-34', 'Good Moral Certificate', 'Good Moral', 'Student', 'off-3', 'OSAS', '12 min'),
  svc('svc-35', 'Issuance of Good Moral Certificate', 'Good Moral', 'Student', 'off-3', 'OSAS', '1 hr, 25 min'),
  svc('svc-37', 'Student Medal Request', 'Administrative', 'Student', 'off-3', 'OSAS', '25 min'),
  svc('svc-38', 'Credentials Service (Transcript of Records)', 'Credentials', 'Student / Alumni', 'off-3', 'OSAS', '2 days'),

  // Academic Office
  svc('svc-18', 'Processing of Application for Change of Enrollment', 'Enrollment', 'Student', 'off-2', 'ACADEMIC_OFFICE', '18 min'),
  svc('svc-19', 'Processing of Application for Cross-Enrollment', 'Enrollment', 'Student', 'off-2', 'ACADEMIC_OFFICE', '10 min'),
  svc('svc-20', 'Processing of Manual Enrollment', 'Enrollment', 'Student', 'off-2', 'ACADEMIC_OFFICE', '2 days'),
  svc('svc-21', 'Processing of Application for Overload of Subjects', 'Enrollment', 'Student', 'off-2', 'ACADEMIC_OFFICE', '7 min'),
  svc('svc-22', 'Processing of Application for Shifting', 'Grade & Records', 'Student', 'off-2', 'ACADEMIC_OFFICE', '27 min'),
  svc('svc-23', 'Processing of Request for Certification (Grades, GWA)', 'Grade & Records', 'Student', 'off-2', 'ACADEMIC_OFFICE', '37 min'),
  svc('svc-24', 'Processing of Course Accreditation (Transferees)', 'Accreditation', 'Student (Transferee)', 'off-2', 'ACADEMIC_OFFICE', '1 day, 5 hrs'),
  svc('svc-39', 'Processing of Online Petition of Subject', 'Enrollment', 'Student', 'off-2', 'ACADEMIC_OFFICE', '45 min'),

  // Administrative Office (Full 39 Services Catalogue from System)
  svc('svc-50', 'Dental Clearance — WITH REFERRAL', 'Dental', 'Student', 'off-1', 'ADMIN_OFFICE', '13 min'),
  svc('svc-51', 'Dental Clearance — WITH REFERRAL (F&A)', 'Dental', 'Faculty & Admin', 'off-1', 'ADMIN_OFFICE', '13 min'),
  svc('svc-52', 'Dental Clearance — WITHOUT REFERRAL', 'Dental', 'Student', 'off-1', 'ADMIN_OFFICE', '9 min'),
  svc('svc-53', 'Dental Clearance — WITHOUT REFERRAL (F&A)', 'Dental', 'Faculty & Admin', 'off-1', 'ADMIN_OFFICE', '9 min'),
  svc('svc-54', 'Emergency Dental Consultation — WITH REFERRAL', 'Dental', 'Faculty & Admin', 'off-1', 'ADMIN_OFFICE', '13 min'),
  svc('svc-55', 'Emergency Dental Consultation — WITH REFERRAL (F&A)', 'Dental', 'Faculty & Admin', 'off-1', 'ADMIN_OFFICE', '13 min'),
  svc('svc-56', 'Emergency Dental Consultation — WITHOUT REFERRAL', 'Dental', 'Student', 'off-1', 'ADMIN_OFFICE', '13 min'),
  svc('svc-57', 'Emergency Dental Consultation — WITHOUT REFERRAL (F&A)', 'Dental', 'Faculty & Admin', 'off-1', 'ADMIN_OFFICE', '13 min'),
  svc('svc-58', 'Non-Emergency Dental Consultation (New Patient)', 'Dental', 'Student', 'off-1', 'ADMIN_OFFICE', '31 min'),
  svc('svc-59', 'Non-Emergency Dental Consultation New Patient (F&A)', 'Dental', 'Faculty & Admin', 'off-1', 'ADMIN_OFFICE', '31 min'),
  svc('svc-60', 'Non-Emergency Dental Consultation (Follow-up)', 'Dental', 'Student', 'off-1', 'ADMIN_OFFICE', '31 min'),
  svc('svc-61', 'Non-Emergency Dental Consultation Follow-up (F&A)', 'Dental', 'Faculty & Admin', 'off-1', 'ADMIN_OFFICE', '31 min'),

  svc('svc-12', 'Campus Equipment / Materials Borrowing', 'Administrative', 'General', 'off-1', 'ADMIN_OFFICE', '15 min'),
  svc('svc-13', 'Facility Reservation Request', 'Administrative', 'General', 'off-1', 'ADMIN_OFFICE', '12 min'),
  svc('svc-14', 'Permission to Conduct an Activity (Activity Permit)', 'Administrative', 'General', 'off-1', 'ADMIN_OFFICE', '15 min'),
  svc('svc-15', 'Library Circulation (Borrowing of Library Materials)', 'Administrative', 'General', 'off-1', 'ADMIN_OFFICE', '5 min'),
  svc('svc-16', 'Academic Verification Service', 'Administrative', 'General', 'off-1', 'ADMIN_OFFICE', '2 days'),
  svc('svc-17', 'Re-Admission Processing (Returning Students)', 'Administrative', 'Student', 'off-1', 'ADMIN_OFFICE', '2 days'),

  svc('svc-1', 'Emergency Medical Consultation — WITH REFERRAL', 'Medical', 'Student', 'off-1', 'ADMIN_OFFICE', '22 min'),
  svc('svc-2', 'Emergency Medical Consultation — WITH REFERRAL (F&A)', 'Medical', 'Faculty & Admin', 'off-1', 'ADMIN_OFFICE', '22 min'),
  svc('svc-3', 'Emergency Medical Consultation — WITHOUT REFERRAL', 'Medical', 'Student', 'off-1', 'ADMIN_OFFICE', '18 min'),
  svc('svc-4', 'Emergency Medical Consultation — WITHOUT REFERRAL (F&A)', 'Medical', 'Faculty & Admin', 'off-1', 'ADMIN_OFFICE', '18 min'),
  svc('svc-5', 'Non-Emergency Medical Consultation (New Patient)', 'Medical', 'Student & Dependents', 'off-1', 'ADMIN_OFFICE', '30 min'),
  svc('svc-6', 'Non-Emergency Medical Consultation New Patient (F&A)', 'Medical', 'Faculty & Admin', 'off-1', 'ADMIN_OFFICE', '30 min'),
  svc('svc-7', 'Non-Emergency Medical Consultation (Follow-up)', 'Medical', 'Student & Dependents', 'off-1', 'ADMIN_OFFICE', '28 min'),
  svc('svc-8', 'Non-Emergency Medical Consultation Follow-up (F&A)', 'Medical', 'Faculty & Admin', 'off-1', 'ADMIN_OFFICE', '28 min'),
  svc('svc-9', 'Medical Certificate — Sick Note / Excuse Slip (Consultation)', 'Medical', 'Student', 'off-1', 'ADMIN_OFFICE', '8 min'),
  svc('svc-10', 'Medical Certificate — Sick Note / Excuse Slip (External)', 'Medical', 'Student', 'off-1', 'ADMIN_OFFICE', '8 min'),
  svc('svc-11', 'Medical Clearance for Enrollment (Normal)', 'Medical', 'Student', 'off-1', 'ADMIN_OFFICE', '15 min'),
  svc('svc-40', 'Medical Clearance for Enrollment — WITH REFERRAL', 'Medical', 'Student', 'off-1', 'ADMIN_OFFICE', '15 min'),
  svc('svc-41', 'Medical Clearance for Food Handlers — WITH REFERRAL', 'Medical', 'Food Handlers', 'off-1', 'ADMIN_OFFICE', '15 min'),
  svc('svc-42', 'Medical Clearance for Food Handlers — WITHOUT REFERRAL', 'Medical', 'Food Handlers', 'off-1', 'ADMIN_OFFICE', '15 min'),
  svc('svc-43', 'Medical Clearance for Off-Campus Activities — WITH REFERRAL', 'Medical', 'Student', 'off-1', 'ADMIN_OFFICE', '15 min'),
  svc('svc-44', 'Medical Clearance for Off-Campus Activities — WITHOUT REFERRAL', 'Medical', 'Student', 'off-1', 'ADMIN_OFFICE', '15 min'),
  svc('svc-45', 'Medical Clearance for OJT — WITH REFERRAL', 'Medical', 'Student', 'off-1', 'ADMIN_OFFICE', '12 min'),
  svc('svc-46', 'Medical Clearance for OJT — WITHOUT REFERRAL', 'Medical', 'Student', 'off-1', 'ADMIN_OFFICE', '12 min'),
  svc('svc-47', 'Annual Medical Clearance — WITH REFERRAL', 'Medical', 'Faculty & Admin', 'off-1', 'ADMIN_OFFICE', '12 min'),
  svc('svc-48', 'Annual Medical Clearance — WITHOUT REFERRAL', 'Medical', 'Faculty & Admin', 'off-1', 'ADMIN_OFFICE', '12 min'),
  svc('svc-49', 'Follow-up of Students Referred During Enrollment', 'Medical', 'Student', 'off-1', 'ADMIN_OFFICE', '15 min'),
]

// ─── Seed Transactions across periods (Q1, Q2, Sem 1, Sem 2, 2026) ─────────────

export const MOCK_TRANSACTIONS: Transaction[] = [
  // OSAS Completed Transactions
  {
    id: 'TXN-1001',
    service_id: 'svc-25',
    service_name: 'Application for New Identification Card',
    service_category: 'ID Services',
    office_id: 'off-3',
    office_name: 'Office of Student Affairs and Services',
    assigned_to: 'user-3',
    assigned_to_name: 'Juan Dela Cruz',
    created_by: 'user-3',
    created_by_name: 'Juan Dela Cruz',
    time_in: '2026-08-10T08:00:00Z',
    time_out: '2026-08-10T08:15:00Z',
    status: 'completed',
    documentary_status: 'complete',
    processing_time_seconds: 900,
    sla_target_seconds: 1800,
    sla_status: 'compliant',
    is_sla_breached: false,
    client_name: 'Maria Clara Santos',
    student_number: '2023-00123-MN-0',
    course: 'BSIT',
    year_level: '3',
    remarks: 'Approved and issued ID',
    is_locked: true,
    created_at: '2026-08-10T08:00:00Z',
    updated_at: '2026-08-10T08:15:00Z',
  },
  {
    id: 'TXN-1002',
    service_id: 'svc-25',
    service_name: 'Application for New Identification Card',
    service_category: 'ID Services',
    office_id: 'off-3',
    office_name: 'Office of Student Affairs and Services',
    assigned_to: 'user-3',
    assigned_to_name: 'Juan Dela Cruz',
    created_by: 'user-3',
    created_by_name: 'Juan Dela Cruz',
    time_in: '2026-08-12T09:00:00Z',
    time_out: '2026-08-12T09:20:00Z',
    status: 'completed',
    documentary_status: 'complete',
    processing_time_seconds: 1200,
    sla_target_seconds: 1800,
    sla_status: 'compliant',
    is_sla_breached: false,
    client_name: 'Jose Rizal Mercado',
    student_number: '2024-00456-MN-0',
    course: 'BSCS',
    year_level: '2',
    remarks: 'Processed successfully',
    is_locked: true,
    created_at: '2026-08-12T09:00:00Z',
    updated_at: '2026-08-12T09:20:00Z',
  },
  {
    id: 'TXN-1003',
    service_id: 'svc-29',
    service_name: 'Issuance of Recommendation Letter',
    service_category: 'Recommendation',
    office_id: 'off-3',
    office_name: 'Office of Student Affairs and Services',
    assigned_to: 'user-3',
    assigned_to_name: 'Juan Dela Cruz',
    created_by: 'user-3',
    created_by_name: 'Juan Dela Cruz',
    time_in: '2026-08-15T10:00:00Z',
    time_out: '2026-08-15T10:35:00Z',
    status: 'completed',
    documentary_status: 'complete',
    processing_time_seconds: 2100,
    sla_target_seconds: 3000,
    sla_status: 'compliant',
    is_sla_breached: false,
    client_name: 'Andres Bonifacio',
    student_number: '2022-00999-MN-0',
    course: 'BSCpE',
    year_level: '4',
    remarks: 'Signed and delivered',
    is_locked: true,
    created_at: '2026-08-15T10:00:00Z',
    updated_at: '2026-08-15T10:35:00Z',
  },
  {
    id: 'TXN-1004',
    service_id: 'svc-30',
    service_name: 'Permission to Conduct an Activity (OSAS)',
    service_category: 'Activity Permit',
    office_id: 'off-3',
    office_name: 'Office of Student Affairs and Services',
    assigned_to: 'user-3',
    assigned_to_name: 'Juan Dela Cruz',
    created_by: 'user-3',
    created_by_name: 'Juan Dela Cruz',
    time_in: '2026-09-01T13:00:00Z',
    time_out: '2026-09-01T14:05:00Z',
    status: 'completed',
    documentary_status: 'complete',
    processing_time_seconds: 3900,
    sla_target_seconds: 4500,
    sla_status: 'compliant',
    is_sla_breached: false,
    client_name: 'PUP Computer Society',
    organization: 'PUP ComSoc',
    remarks: 'Activity permit approved',
    is_locked: true,
    created_at: '2026-09-01T13:00:00Z',
    updated_at: '2026-09-01T14:05:00Z',
  },
  {
    id: 'TXN-1005',
    service_id: 'svc-31',
    service_name: 'Processing of Application for Student Fund-Raising',
    service_category: 'Activity Permit',
    office_id: 'off-3',
    office_name: 'Office of Student Affairs and Services',
    assigned_to: 'user-3',
    assigned_to_name: 'Juan Dela Cruz',
    created_by: 'user-3',
    created_by_name: 'Juan Dela Cruz',
    time_in: '2026-09-10T08:00:00Z',
    time_out: '2026-09-10T15:30:00Z',
    status: 'completed',
    documentary_status: 'complete',
    processing_time_seconds: 27000,
    sla_target_seconds: 28800,
    sla_status: 'compliant',
    is_sla_breached: false,
    client_name: 'PUP Red Cross Youth',
    organization: 'RCY',
    remarks: 'Fundraising permit verified',
    is_locked: true,
    created_at: '2026-09-10T08:00:00Z',
    updated_at: '2026-09-10T15:30:00Z',
  },

  // Academic Office Completed Transactions
  {
    id: 'TXN-2001',
    service_id: 'svc-18',
    service_name: 'Processing of Application for Change of Enrollment',
    service_category: 'Enrollment',
    office_id: 'off-2',
    office_name: 'Academic Office',
    assigned_to: 'user-2',
    assigned_to_name: 'Prof. Ana Mabini',
    created_by: 'user-2',
    created_by_name: 'Prof. Ana Mabini',
    time_in: '2026-08-05T08:30:00Z',
    time_out: '2026-08-05T08:42:00Z',
    status: 'completed',
    documentary_status: 'complete',
    processing_time_seconds: 720,
    sla_target_seconds: 1080,
    sla_status: 'compliant',
    is_sla_breached: false,
    client_name: 'Emilio Aguinaldo',
    student_number: '2025-00111-MN-0',
    course: 'BSIT',
    year_level: '1',
    remarks: 'Subject adjusted',
    is_locked: true,
    created_at: '2026-08-05T08:30:00Z',
    updated_at: '2026-08-05T08:42:00Z',
  },
  {
    id: 'TXN-2002',
    service_id: 'svc-22',
    service_name: 'Processing of Application for Shifting',
    service_category: 'Grade & Records',
    office_id: 'off-2',
    office_name: 'Academic Office',
    assigned_to: 'user-2',
    assigned_to_name: 'Prof. Ana Mabini',
    created_by: 'user-2',
    created_by_name: 'Prof. Ana Mabini',
    time_in: '2026-08-11T10:00:00Z',
    time_out: '2026-08-11T10:20:00Z',
    status: 'completed',
    documentary_status: 'complete',
    processing_time_seconds: 1200,
    sla_target_seconds: 1620,
    sla_status: 'compliant',
    is_sla_breached: false,
    client_name: 'Apolinario Mabini',
    student_number: '2024-00222-MN-0',
    course: 'BSBA',
    year_level: '2',
    remarks: 'Shifting evaluation approved',
    is_locked: true,
    created_at: '2026-08-11T10:00:00Z',
    updated_at: '2026-08-11T10:20:00Z',
  },
  {
    id: 'TXN-2003',
    service_id: 'svc-24',
    service_name: 'Processing of Course Accreditation (Transferees)',
    service_category: 'Accreditation',
    office_id: 'off-2',
    office_name: 'Academic Office',
    assigned_to: 'user-2',
    assigned_to_name: 'Prof. Ana Mabini',
    created_by: 'user-2',
    created_by_name: 'Prof. Ana Mabini',
    time_in: '2026-08-20T09:00:00Z',
    time_out: '2026-08-21T11:00:00Z',
    status: 'completed',
    documentary_status: 'complete',
    processing_time_seconds: 36000,
    sla_target_seconds: 46800,
    sla_status: 'compliant',
    is_sla_breached: false,
    client_name: 'Melchora Aquino',
    student_number: '2026-00888-MN-0',
    course: 'BSIT',
    year_level: '1',
    remarks: 'Credited 18 units',
    is_locked: true,
    created_at: '2026-08-20T09:00:00Z',
    updated_at: '2026-08-21T11:00:00Z',
  },
  {
    id: 'TXN-2004',
    service_id: 'svc-39',
    service_name: 'Processing of Online Petition of Subject',
    service_category: 'Enrollment',
    office_id: 'off-2',
    office_name: 'Academic Office',
    assigned_to: 'user-2',
    assigned_to_name: 'Prof. Ana Mabini',
    created_by: 'user-2',
    created_by_name: 'Prof. Ana Mabini',
    time_in: '2026-09-02T11:00:00Z',
    time_out: '2026-09-02T11:35:00Z',
    status: 'completed',
    documentary_status: 'complete',
    processing_time_seconds: 2100,
    sla_target_seconds: 2700,
    sla_status: 'compliant',
    is_sla_breached: false,
    client_name: 'Gabriele Silang',
    student_number: '2023-00555-MN-0',
    course: 'BSCS',
    year_level: '3',
    remarks: 'Petition granted',
    is_locked: true,
    created_at: '2026-09-02T11:00:00Z',
    updated_at: '2026-09-02T11:35:00Z',
  },

  // Administrative Office Completed Transactions
  {
    id: 'TXN-3001',
    service_id: 'svc-12',
    service_name: 'Campus Equipment / Materials Borrowing',
    service_category: 'Administrative',
    office_id: 'off-1',
    office_name: 'Administrative Office',
    assigned_to: 'user-1',
    assigned_to_name: 'Admin Admin',
    created_by: 'user-1',
    created_by_name: 'Admin Admin',
    time_in: '2026-08-08T09:00:00Z',
    time_out: '2026-08-08T09:10:00Z',
    status: 'completed',
    documentary_status: 'complete',
    processing_time_seconds: 600,
    sla_target_seconds: 900,
    sla_status: 'compliant',
    is_sla_breached: false,
    client_name: 'Marcelo H. Del Pilar',
    remarks: 'Projector released',
    is_locked: true,
    created_at: '2026-08-08T09:00:00Z',
    updated_at: '2026-08-08T09:10:00Z',
  },
  {
    id: 'TXN-3002',
    service_id: 'svc-13',
    service_name: 'Facility Reservation Request',
    service_category: 'Administrative',
    office_id: 'off-1',
    office_name: 'Administrative Office',
    assigned_to: 'user-1',
    assigned_to_name: 'Admin Admin',
    created_by: 'user-1',
    created_by_name: 'Admin Admin',
    time_in: '2026-08-14T14:00:00Z',
    time_out: '2026-08-14T14:08:00Z',
    status: 'completed',
    documentary_status: 'complete',
    processing_time_seconds: 480,
    sla_target_seconds: 720,
    sla_status: 'compliant',
    is_sla_breached: false,
    client_name: 'Gregoria de Jesus',
    remarks: 'AVR 1 Reserved',
    is_locked: true,
    created_at: '2026-08-14T14:00:00Z',
    updated_at: '2026-08-14T14:08:00Z',
  },
  {
    id: 'TXN-3003',
    service_id: 'svc-16',
    service_name: 'Academic Verification Service',
    service_category: 'Administrative',
    office_id: 'off-1',
    office_name: 'Administrative Office',
    assigned_to: 'user-1',
    assigned_to_name: 'Admin Admin',
    created_by: 'user-1',
    created_by_name: 'Admin Admin',
    time_in: '2026-09-05T08:00:00Z',
    time_out: '2026-09-06T10:00:00Z',
    status: 'completed',
    documentary_status: 'complete',
    processing_time_seconds: 36000,
    sla_target_seconds: 64200,
    sla_status: 'compliant',
    is_sla_breached: false,
    client_name: 'Juan Luna Enterprise',
    remarks: 'Verification response dispatched',
    is_locked: true,
    created_at: '2026-09-05T08:00:00Z',
    updated_at: '2026-09-06T10:00:00Z',
  },
]

export const MOCK_HISTORY: TransactionStatusHistory[] = []
